webapp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import InputRequired, Email, Length, ValidationError
from webapp.db_models import User


class LoginForm(FlaskForm):
    username = StringField('username', validators=[InputRequired(), Length(min=4, max=24)])
    password = PasswordField('password', validators=[InputRequired(), Length(min=8, max=80)])
    remember = BooleanField('remember me')


class RegisterForm(FlaskForm):
    email = StringField('email', validators=[InputRequired(), Email(message='Invalid email'), Length(max=50)])
    username = StringField('username', validators=[InputRequired(), Length(min=4, max=24)])
    password = PasswordField('password', validators=[InputRequired(), Length(min=8, max=80)])

    def check_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is already taken. Please choose another.')

    def check_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is already taken. Please choose another')

webapp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from webapp.config import Config
from flask_bootstrap import Bootstrap
from flask_apscheduler import APScheduler

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message = "You need to be logged in to view this page"
login_manager.login_message_category = "info"
mail = Mail()
scheduler = APScheduler()
scheduler.api_enabled = True


def create_app(config=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    bootstrap = Bootstrap(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    scheduler.init_app(app)
    scheduler.start()


    from webapp.users.routes import users_bp
    from webapp.posts.routes import posts_bp
    from webapp.main.routes import main_bp
    from webapp.crypto.routes import cryptos_bp
    app.register_blueprint(users_bp)
    app.register_blueprint(posts_bp)
    app.register_blueprint(main_bp)
    app.register_blueprint(cryptos_bp)

    return app

webapp/crypto/routes.py
from flask import render_template, Blueprint
from webapp import db, scheduler
from webapp.db_models import Crypto
from .crypto_api import get_crypto_info

cryptos_bp = Blueprint('crypto', __name__)


@cryptos_bp.route("/crypto")
def crypto():
    query = Crypto.query.order_by(Crypto.id.asc()).all()
    return render_template("crypto.html", query=query)


@scheduler.task('interval', id='update', minutes=1, misfire_grace_time=900)
def update():
    cryptos = get_crypto_info()
    app = scheduler.app
    with app.app_context():
        if db.session.query(Crypto).first() is None:
            for crypto in cryptos:
                cryptocurrency = Crypto(name=crypto['name'], symbol=crypto['symbol'], price=crypto['price'],
                                        percent_change_24h=crypto['percent_change_24h'],
                                        market_cap=crypto['market_cap'])
                db.session.add(cryptocurrency)
        else:
            for crypto in cryptos:
                for row in Crypto.query:
                    if row.name == crypto['name']:
                        row.price = crypto['price']
                        row.percent_change_24h = crypto['percent_change_24h']
                        row.market_cap = crypto['market_cap']

        db.session.commit()

webapp/main/routes.py
from flask import render_template, request, Blueprint
from webapp.db_models import Blogpost
from .utility import sendContactForm

main_bp = Blueprint('main', __name__)


@main_bp.route('/')
def index():
    posts = Blogpost.query.filter(Blogpost.id < 8)

    return render_template('index.html', posts=posts)


@main_bp.route("/contact", methods=['GET', 'POST'])
def contact():
    if request.method == 'POST':
        result = {}
        result['name'] = request.form['name']
        result['email'] = request.form['email'].replace(' ', '').lower()
        result['message'] = request.form['message']

        response = sendContactForm(result)

        return render_template('contact.html', response=response)

    return render_template('contact.html')

webapp/posts/routes.py
from flask import render_template, redirect, url_for, request, Blueprint
from datetime import datetime
from webapp import db
from webapp.db_models import Blogpost


posts_bp = Blueprint('posts', __name__)

@posts_bp.route('/posts')
def view_posts():
    all_posts = Blogpost.query.order_by(Blogpost.date_posted.desc()).all()

    return render_template('posts.html', posts=all_posts)


@posts_bp.route('/post/<int:post_id>')
def post(post_id):
    post = Blogpost.query.filter_by(id=post_id).one()

    return render_template('post.html', post=post)


@posts_bp.route('/addpost', methods=['GET', 'POST'])
def add_post():
    if request.method == 'POST':
        title = request.form['title']
        subtitle = request.form['subtitle']
        author = request.form['author']
        content = request.form['content']

        post = Blogpost(title=title, subtitle=subtitle, author=author, content=content, date_posted=datetime.now())

        db.session.add(post)
        db.session.commit()

        return redirect(url_for('posts.view_posts'))
    return render_template('add.html')

webapp/users/routes.py
from flask import render_template, url_for, redirect, Blueprint
from flask_login import login_user, login_required, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from webapp import db
from webapp.db_models import User
from webapp.users.forms import RegisterForm, LoginForm

users_bp = Blueprint('users', __name__)


@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                return redirect(url_for('users.view'))
        else:
            invalid = True
            return render_template('login.html', invalid=invalid, form=form)

    return render_template('login.html', form=form)


@users_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = RegisterForm()

    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        return render_template('newuser.html')

    return render_template('signup.html', form=form)


@users_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users_bp.route('/view')
@login_required
def view():
    return render_template('view.html', values=User.query.all())

webapp/templates/add.html
{% extends "base.html" %}


{% block title %}
<h1>Add post</h1>
{% endblock %}

{% block content %}
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <form name="addForm" id="addForm" method="POST" action="{{ url_for('posts.add_post') }}" novalidate>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Title</label>
                <input type="text" class="form-control" placeholder="Title" name="title" id="title" required data-validation-required-message="Please enter a title.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Subtitle</label>
                <input type="text" class="form-control" placeholder="Subtitle" name="subtitle" id="subtitle" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>Author</label>
                <input type="text" class="form-control" placeholder="Author" name="author" id="author" required data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Blog Content</label>
                <textarea rows="5" class="form-control" placeholder="Blog content" name="content" id="content" required data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
            <div class="form-group">
              <button type="submit" class="btn btn-primary" id="sendMessageButton">Add</button>
            </div>
          </form>
        </div>
      </div>
    </div>
<hr>
{% endblock %}

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Crypto Blog</title>

    <!-- Favicons -->
  <link href="/static/img/favicon.png" rel="icon">
  <link href="/static/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Bootstrap core CSS -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="/static/css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="/">Crypto Blog</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.view')}}">Users</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('posts.view_posts')}}">Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('crypto.crypto')}}">Crypto</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('main.contact')}}">Contact</a>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('/static/img/home-bg.jpg')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            {% block title %}

            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->


        {% block content %}

          {% endblock %}


  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="https://twitter.com/corkiam" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.facebook.com/cosmin.veh/" target="_blank" >
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.com/Corkian" target="_blank">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Crypto Blog 2021</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="/static/js/clean-blog.min.js"></script>

</body>

</html>

webapp/templates/contact.html
{% extends "base.html" %}
{% block content %}

 <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% if response %}
        <h4>Email has been sent. Thank you!</h4>
        {% endif %}
        <h4></h4>
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <form name="sentMessage" id="contactForm" method="POST" action="/contact">
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" name="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" name="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" name="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <hr>
          {% endblock %}

webapp/templates/crypto.html
{% extends "base.html" %}


{% block title %}
<h1>The Top 100 Crypto</h1>
{% endblock %}

{% block content %}
<link href="/static/css/table.css" rel="stylesheet">
<div class="container">

    <div class="col-lg-8 col-md-10 mx-auto">
        <h2 style="margin-bottom:20px">May The Odds Be With You</h2>


        <sub><em>*Table contents is being updated every minute via CoinMarketCap's API</em></sub>
        <div id="table">
            <table class="content-table">

                <thead>
                <tr>
                    <th>Name</th>
                    <th>Symbol</th>
                    <th>Price</th>
                    <th>24h % change</th>
                    <th>Market Cap</th>
                </tr>
                </thead>

                <tbody>
                {% for crypto in query %}
                <tr>
                    <td>{{crypto.name}}</td>
                    <td>{{crypto.symbol}}</td>
                    <td>{{"${:,.2f}".format(crypto.price)}}</td>
                    <td
                    {% if crypto.percent_change_24h < 0 %} class="bear" {% else %} class="bull" {% endif
                    %}>{{crypto.percent_change_24h}}%</td>
                    <td>{{ "${:,}".format(crypto.market_cap)}}</td>
                </tr>
                <tr>
                    {% endfor %}
                </tr>
                </tbody>

            </table>
        </div>
    </div>
</div>
<hr>
<script type=text/javascript>
setInterval(function()
{
$('#table').load(document.URL +  ' #table');
}, 30000)

</script>

{% endblock %}

webapp/templates/index.html
{% extends "base.html" %}

{% block title %}
<h1>Cryptocurrency Blog</h1>
<span class="subheading">News, updates and industry insights</span>
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% for post in posts %}
            <div class="post-preview">
                <a href="{{ url_for('posts.post', post_id=post.id) }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ post.subtitle }}
                    </h3>
                </a>
                <p class="post-meta">Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
            </div>
            <hr>
            {% endfor %}

        </div>

    </div>
    <div class="clearfix">
        <a class="btn btn-primary float-right" href="posts">All Posts &rarr;</a>
    </div>
</div>
<hr>
{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
<h1>Login</h1>

{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

            {% if current_user.is_authenticated %}
            <h2 class="form-signin-heading">You are already logged in as {{ current_user.username }}</h2>
            {% else %}
            <div class="container">

                <form class="form-signin" method="POST" action="/login">
                    {% if invalid %}
                    <h2 class="form-signin-heading">Username or password invalid</h2>
                    {% else %}
                    <h2 class="form-signin-heading">Please sign in</h2>
                     {% endif %}
                    {{ form.hidden_tag() }}
                    {{ wtf.form_field(form.username) }}
                    {{ wtf.form_field(form.password) }}
                    {{ wtf.form_field(form.remember) }}
                    <button class="btn btn-primary" type="submit">Sign in</button>
                    <a class="btn btn-secondary" href="signup">Register</a>
                </form>
            </div>
            {% endif %}
<hr>
            {% endblock %}

webapp/templates/newuser.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
 {% block title %}
            <h1>Your account has been created</h1>
            {% endblock %}
    {% block content %}
 <div class="container">
<h2 style="text-align:center">You can login now</h2>

{% endblock %}

webapp/templates/post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
<h1>Blogpost</h1>
{% endblock %}

{% block content %}


      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ post.title }}</h1>
              <h2 class="post-subtitle">{{ post.subtitle }}</h2>
              <span>Posted by
                {{ post.author }}
                on {{ post.date_posted.strftime('%B %d, %Y') }}</span>
            </div>
          </div>
        </div>
      </div>


    <!-- Post Content -->
    <article style="margin:40px">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.content|safe }}
          </div>
        </div>
      </div>
    </article>

    <hr>
{% endblock %}

webapp/templates/posts.html
{% extends "base.html" %}


{% block title %}
<h1>All Posts</h1>
{% endblock %}

{% block content %}
    <!-- Page Header -->
     <div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <a class="btn btn-primary" href="addpost">Add Post</a>
            {% for post in posts %}
            <div class="post-preview">
                <a href="{{ url_for('posts.post', post_id=post.id) }}">
                    <h2 class="post-title">
                        {{ post.title }}
                    </h2>
                    <h3 class="post-subtitle">
                        {{ post.subtitle }}
                    </h3>
                </a>
                <p class="post-meta">Posted by {{ post.author }} on {{ post.date_posted.strftime('%B %d, %Y') }}</p>
            </div>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>
<hr>
{% endblock %}

webapp/templates/signup.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
 <div class="container">

  <form class="form-signin" method="POST" action="/signup">
    <h2 class="form-signin-heading">Sign Up</h2>
    {{ form.hidden_tag() }}
    {{ wtf.form_field(form.username) }}
    {{ wtf.form_field(form.email) }}
    {{ wtf.form_field(form.password) }}
    <button class="btn btn-primary" type="submit">Sign Up</button>
  </form>

{% endblock %}

webapp/templates/view.html
{% extends "base.html" %}

            {% block title %}
            <h1>Members</h1>
            {% endblock %}

{% block content %}

 <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">

    {% for item in values %}
        <p>Name: {{item.username}}</p>
        <p>Email: {{item.email}}</p>
<hr>
 {% endfor %}
{% endblock %}